CREATE TABLE Books(
	id INT NOT NULL AUTO_INCREMENT,
	title VARCHAR(255) NOT NULL,
	status VARCHAR(255) NOT NULL,
	PRIMARY KEY(id)
);

CREATE TABLE Users(
	id INT NOT NULL AUTO_INCREMENT,
	first_name VARCHAR(255) NOT NULL,
	last_name VARCHAR(255) NOT NULL,
	email VARCHAR(255) UNIQUE NOT NULL,
	password VARCHAR(255) NOT NULL,
	role VARCHAR(255) NOT NULL,
	PRIMARY KEY(id)
);

CREATE TABLE Issues(
	id INT NOT NULL AUTO_INCREMENT,
	user_id INT NOT NULL,
	book_id INT NOT NULL,
	issue_date DATE NOT NULL,
	PRIMARY KEY(id),
	CONSTRAINT FK_UserIssue FOREIGN KEY(user_id) REFERENCES Users(id),
	CONSTRAINT FK_BookIssue FOREIGN KEY(book_id) REFERENCES Books(id)
);

CREATE TABLE Returns(
	id INT NOT NULL AUTO_INCREMENT,
	user_id INT NOT NULL,
	book_id INT NOT NULL,
	issue_date DATE NOT NULL,
	return_date DATE NOT NULL,
	PRIMARY KEY(id),
	CONSTRAINT FK_UserReturn FOREIGN KEY(user_id) REFERENCES Users(id),
	CONSTRAINT FK_BookReturn FOREIGN KEY(book_id) REFERENCES Books(id)
);